export enum VariantType {
  SIZE = "SIZE",
  BASE = "BASE",
  FILLING = "FILLING",
  CREAM = "CREAM",
  TOP_EDGE = "TOP_EDGE",
  BOTTOM_EDGE = "BOTTOM_EDGE",
  DECORATION = "DECORATION",
  SURFACE = "SURFACE",
}
